
package com.mycompany.ejercicio_figuras;

/**
 *
 * @author Gianca
 */
public class Pantalla_figuras extends javax.swing.JFrame {

    /**
     * Creates new form Pantalla_figuras
     */
    public Pantalla_figuras() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCRadio = new javax.swing.JTextField();
        txtCArea = new javax.swing.JTextField();
        txtCPerimetro = new javax.swing.JTextField();
        btnAreaC = new javax.swing.JButton();
        btnPerimetroC = new javax.swing.JButton();
        btnPerimetroT = new javax.swing.JButton();
        btnBorrarC = new javax.swing.JButton();
        btnBorrarT = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtTPerimetro = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtTTipo = new javax.swing.JTextField();
        bntTipoT = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        txtTraArea = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCuLado = new javax.swing.JTextField();
        txtCuArea = new javax.swing.JTextField();
        txtCuPerimetro = new javax.swing.JTextField();
        btnAreaCu = new javax.swing.JButton();
        txtTraPerimetro = new javax.swing.JTextField();
        btnPerimetroCu = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        btnBorrarCu = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtTraBase1 = new javax.swing.JTextField();
        txtTraBase2 = new javax.swing.JTextField();
        txtTraAltura = new javax.swing.JTextField();
        btnAreaTra = new javax.swing.JButton();
        btnPerimetroTra = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtRBase = new javax.swing.JTextField();
        txtRAltura = new javax.swing.JTextField();
        txtRArea = new javax.swing.JTextField();
        btnAreaR = new javax.swing.JButton();
        btnBorrarTra = new javax.swing.JButton();
        btnPerimetroR = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        btnBorrarR = new javax.swing.JButton();
        txtRoPerimetro = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txtRoDiagonal1 = new javax.swing.JTextField();
        txtRoDiagonal2 = new javax.swing.JTextField();
        txtRoArea = new javax.swing.JTextField();
        btnAreaRo = new javax.swing.JButton();
        btnPerimetroRo = new javax.swing.JButton();
        btnBorrarRo = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txtRPerimetro = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtTBase = new javax.swing.JTextField();
        txtTAltura = new javax.swing.JTextField();
        txtTArea = new javax.swing.JTextField();
        btnAreaT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Radio");

        jLabel2.setText("Area");

        jLabel3.setText("Perimetro");

        txtCRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCRadioActionPerformed(evt);
            }
        });

        txtCArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCAreaActionPerformed(evt);
            }
        });

        btnAreaC.setText("Calcular Area");
        btnAreaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAreaCActionPerformed(evt);
            }
        });

        btnPerimetroC.setText("Calcular Perimetro");
        btnPerimetroC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerimetroCActionPerformed(evt);
            }
        });

        btnPerimetroT.setText("Calcular Perimetro");
        btnPerimetroT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerimetroTActionPerformed(evt);
            }
        });

        btnBorrarC.setText("Borrar");
        btnBorrarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarCActionPerformed(evt);
            }
        });

        btnBorrarT.setText("Borrar");
        btnBorrarT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarTActionPerformed(evt);
            }
        });

        jLabel4.setText("Circulo");

        jLabel18.setText("Perimetro");

        jLabel19.setText("Tipo");

        bntTipoT.setText("Definir que tipo de triangiulo");
        bntTipoT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntTipoTActionPerformed(evt);
            }
        });

        jLabel20.setText("Area");

        jLabel21.setText("Perimetro");

        jLabel5.setText("Cuadrado");

        jLabel6.setText("Lado");

        jLabel7.setText("Area");

        jLabel8.setText("Perimetro");

        txtCuLado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCuLadoActionPerformed(evt);
            }
        });

        txtCuArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCuAreaActionPerformed(evt);
            }
        });

        btnAreaCu.setText("Calcular Area");
        btnAreaCu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAreaCuActionPerformed(evt);
            }
        });

        btnPerimetroCu.setText("Calcular Perimetro");
        btnPerimetroCu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerimetroCuActionPerformed(evt);
            }
        });

        jLabel22.setText("Trapecio");

        btnBorrarCu.setText("Borrar");
        btnBorrarCu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarCuActionPerformed(evt);
            }
        });

        jLabel23.setText("Base 1");

        jLabel24.setText("Base 2");

        jLabel25.setText("Altura");

        txtTraBase1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTraBase1ActionPerformed(evt);
            }
        });

        txtTraBase2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTraBase2ActionPerformed(evt);
            }
        });

        btnAreaTra.setText("Calcular Area");
        btnAreaTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAreaTraActionPerformed(evt);
            }
        });

        btnPerimetroTra.setText("Calcular Perimetro");
        btnPerimetroTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerimetroTraActionPerformed(evt);
            }
        });

        jLabel9.setText("Rectangulo");

        jLabel10.setText("Base");

        jLabel11.setText("Altura");

        jLabel12.setText("Area");

        txtRBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRBaseActionPerformed(evt);
            }
        });

        txtRAltura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRAlturaActionPerformed(evt);
            }
        });

        btnAreaR.setText("Calcular Area");
        btnAreaR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAreaRActionPerformed(evt);
            }
        });

        btnBorrarTra.setText("Borrar");
        btnBorrarTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarTraActionPerformed(evt);
            }
        });

        btnPerimetroR.setText("Calcular Perimetro");
        btnPerimetroR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerimetroRActionPerformed(evt);
            }
        });

        jLabel26.setText("Perimetro");

        btnBorrarR.setText("Borrar");
        btnBorrarR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarRActionPerformed(evt);
            }
        });

        jLabel28.setText("Rombo");

        jLabel29.setText("Diagonal 1");

        jLabel30.setText("Diagonal 2");

        jLabel31.setText("Area");

        txtRoDiagonal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRoDiagonal1ActionPerformed(evt);
            }
        });

        txtRoDiagonal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRoDiagonal2ActionPerformed(evt);
            }
        });

        btnAreaRo.setText("Calcular Area");
        btnAreaRo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAreaRoActionPerformed(evt);
            }
        });

        btnPerimetroRo.setText("Calcular Perimetro");
        btnPerimetroRo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerimetroRoActionPerformed(evt);
            }
        });

        btnBorrarRo.setText("Borrar");
        btnBorrarRo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarRoActionPerformed(evt);
            }
        });

        jLabel13.setText("Perimetro");

        jLabel14.setText("Triangulo");

        jLabel15.setText("Base");

        jLabel16.setText("Altura");

        jLabel17.setText("Area");

        txtTBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTBaseActionPerformed(evt);
            }
        });

        txtTAltura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTAlturaActionPerformed(evt);
            }
        });

        btnAreaT.setText("Calcular Area");
        btnAreaT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAreaTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAreaR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPerimetroR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBorrarR))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtRBase, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtRAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(72, 72, 72)
                                .addComponent(txtRArea, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(44, 44, 44)
                                .addComponent(txtRPerimetro, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(139, 139, 139)
                                .addComponent(jLabel9))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(44, 44, 44)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(43, 43, 43)
                                                .addComponent(jLabel4)
                                                .addGap(131, 131, 131))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtCPerimetro, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtCRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtCArea, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAreaC)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnPerimetroC)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBorrarC)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(btnAreaT)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnPerimetroT)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnBorrarT))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(96, 96, 96)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtTBase, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtTAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(139, 139, 139)
                                    .addComponent(jLabel14))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtTTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel16)
                                        .addComponent(jLabel15)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel17)
                                            .addGap(72, 72, 72)
                                            .addComponent(txtTArea, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel18)
                                            .addGap(44, 44, 44)
                                            .addComponent(txtTPerimetro, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGap(64, 64, 64)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addGap(44, 44, 44)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtCuPerimetro, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtCuLado, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtCuArea, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnAreaCu)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnPerimetroCu)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnBorrarCu))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(160, 160, 160)
                            .addComponent(jLabel5)
                            .addGap(112, 112, 112))))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAreaRo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnPerimetroRo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBorrarRo))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAreaTra)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnPerimetroTra)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBorrarTra)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(96, 96, 96)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtTraBase1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtTraBase2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtTraArea, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(139, 139, 139)
                                        .addComponent(jLabel22))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel21)
                                            .addGap(44, 44, 44)
                                            .addComponent(txtTraPerimetro, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel24)
                                                .addComponent(jLabel23)
                                                .addComponent(jLabel25)
                                                .addComponent(jLabel20))
                                            .addGap(63, 63, 63)
                                            .addComponent(txtTraAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(8, 8, 8))))
                                .addGap(92, 92, 92))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(96, 96, 96)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtRoDiagonal1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtRoDiagonal2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(139, 139, 139)
                                        .addComponent(jLabel28))
                                    .addComponent(jLabel30)
                                    .addComponent(jLabel29)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel31)
                                        .addGap(72, 72, 72)
                                        .addComponent(txtRoArea, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel26)
                                        .addGap(44, 44, 44)
                                        .addComponent(txtRoPerimetro, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(98, 98, 98))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bntTipoT)
                .addGap(421, 421, 421))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(txtRoDiagonal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(txtRoDiagonal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel31)
                            .addComponent(txtRoArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(txtRoPerimetro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAreaRo)
                            .addComponent(btnPerimetroRo)
                            .addComponent(btnBorrarRo))
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtCuLado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtCuArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtCuPerimetro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAreaCu)
                            .addComponent(btnPerimetroCu)
                            .addComponent(btnBorrarCu))
                        .addGap(44, 44, 44)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(txtTBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(txtTAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(txtTArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(txtTPerimetro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(txtTTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAreaT)
                            .addComponent(btnPerimetroT)
                            .addComponent(btnBorrarT)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(txtTraBase1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(txtTraBase2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(txtTraAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(txtTraArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTraPerimetro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAreaTra)
                            .addComponent(btnPerimetroTra)
                            .addComponent(btnBorrarTra))))
                .addGap(2, 2, 2)
                .addComponent(bntTipoT)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCRadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCPerimetro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAreaC)
                    .addComponent(btnPerimetroC)
                    .addComponent(btnBorrarC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtRBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtRAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtRArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtRPerimetro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAreaR)
                    .addComponent(btnPerimetroR)
                    .addComponent(btnBorrarR))
                .addGap(54, 54, 54))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCRadioActionPerformed

    private void txtCAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCAreaActionPerformed

    private void btnAreaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAreaCActionPerformed
        // TODO add your handling code here:

        double area;
        int radio = Integer.parseInt(txtCRadio.getText());
        Circulo figura1 = new Circulo(radio);
        area = figura1.calcularArea();
        txtCArea.setText(String.valueOf(area));
    }//GEN-LAST:event_btnAreaCActionPerformed

    private void btnPerimetroCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerimetroCActionPerformed
        // TODO add your handling code here:

        double perimetro;
        int radio = Integer.parseInt(txtCRadio.getText());
        Circulo figura1 = new Circulo(radio);
        perimetro = figura1.calcularPerimetro();
        txtCPerimetro.setText(String.valueOf(perimetro));
    }//GEN-LAST:event_btnPerimetroCActionPerformed

    private void btnPerimetroTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerimetroTActionPerformed
        // TODO add your handling code here:

        double perimetro;
        int base = Integer.parseInt(txtTBase.getText());
        int altura = Integer.parseInt(txtTAltura.getText());
        TrianguloRectangulo figura4 = new TrianguloRectangulo(base,altura);
        perimetro = figura4.calcularPerimetro();
        txtTPerimetro.setText(String.valueOf(perimetro));

    }//GEN-LAST:event_btnPerimetroTActionPerformed

    private void btnBorrarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarCActionPerformed
        // TODO add your handling code here:

        txtCRadio.setText("");
        txtCArea.setText("");
        txtCPerimetro.setText("");

    }//GEN-LAST:event_btnBorrarCActionPerformed

    private void btnBorrarTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarTActionPerformed
        // TODO add your handling code here:

        txtTBase.setText("");
        txtTAltura.setText("");
        txtTArea.setText("");
        txtTPerimetro.setText("");
        txtTTipo.setText("");

    }//GEN-LAST:event_btnBorrarTActionPerformed

    private void bntTipoTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntTipoTActionPerformed
        // TODO add your handling code here:

        int base = Integer.parseInt(txtTBase.getText());
        int altura = Integer.parseInt(txtTAltura.getText());
        TrianguloRectangulo figura4 = new TrianguloRectangulo(base,altura);
        txtTTipo.setText(figura4.determinarTipoTriangulo());

    }//GEN-LAST:event_bntTipoTActionPerformed

    private void txtCuLadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCuLadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCuLadoActionPerformed

    private void txtCuAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCuAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCuAreaActionPerformed

    private void btnAreaCuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAreaCuActionPerformed
        // TODO add your handling code here:

        double area;
        int lado = Integer.parseInt(txtCuLado.getText());
        Cuadrado figura3 = new Cuadrado(lado);
        area = figura3.calcularArea();
        txtCuArea.setText(String.valueOf(area));
    }//GEN-LAST:event_btnAreaCuActionPerformed

    private void btnPerimetroCuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerimetroCuActionPerformed
        // TODO add your handling code here:
        double perimetro;
        int lado = Integer.parseInt(txtCuLado.getText());
        Cuadrado figura3 = new Cuadrado(lado);
        perimetro = figura3.calcularPerimetro();
        txtCuPerimetro.setText(String.valueOf(perimetro));

    }//GEN-LAST:event_btnPerimetroCuActionPerformed

    private void btnBorrarCuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarCuActionPerformed
        // TODO add your handling code here:
        txtCuLado.setText("");
        txtCuArea.setText("");
        txtCuPerimetro.setText("");
    }//GEN-LAST:event_btnBorrarCuActionPerformed

    private void txtTraBase1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTraBase1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTraBase1ActionPerformed

    private void txtTraBase2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTraBase2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTraBase2ActionPerformed

    private void btnAreaTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAreaTraActionPerformed
        // TODO add your handling code here:
        double area;
        int base1 = Integer.parseInt(txtTraBase1.getText());
        int base2 = Integer.parseInt(txtTraBase2.getText());
        int altura = Integer.parseInt(txtTraAltura.getText());
        Trapecio figura6 = new Trapecio(base1,base2,altura);
        area = figura6.calcularArea();
        txtTraArea.setText(String.valueOf(area));
    }//GEN-LAST:event_btnAreaTraActionPerformed

    private void btnPerimetroTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerimetroTraActionPerformed
        // TODO add your handling code here:
        double perimetro;
        int base1 = Integer.parseInt(txtTraBase1.getText());
        int base2 = Integer.parseInt(txtTraBase2.getText());
        int altura = Integer.parseInt(txtTraAltura.getText());
        Trapecio figura6 = new Trapecio(base1,base2,altura);
        perimetro = figura6.calcularPerimetro();
        txtTraPerimetro.setText(String.valueOf(perimetro));
    }//GEN-LAST:event_btnPerimetroTraActionPerformed

    private void txtRBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRBaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRBaseActionPerformed

    private void txtRAlturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRAlturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRAlturaActionPerformed

    private void btnAreaRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAreaRActionPerformed
        // TODO add your handling code here:

        double area;
        int base = Integer.parseInt(txtRBase.getText());
        int altura = Integer.parseInt(txtRAltura.getText());
        Rectangulo figura2 = new Rectangulo(base,altura);
        area = figura2.calcularArea();
        txtRArea.setText(String.valueOf(area));

    }//GEN-LAST:event_btnAreaRActionPerformed

    private void btnBorrarTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarTraActionPerformed
        // TODO add your handling code here:
        txtTraBase1.setText("");
        txtTraBase2.setText("");
        txtTraAltura.setText("");
        txtTraArea.setText("");
        txtTraPerimetro.setText("");
    }//GEN-LAST:event_btnBorrarTraActionPerformed

    private void btnPerimetroRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerimetroRActionPerformed
        // TODO add your handling code here:

        double perimetro;
        int base = Integer.parseInt(txtRBase.getText());
        int altura = Integer.parseInt(txtRAltura.getText());
        Rectangulo figura2 = new Rectangulo(base,altura);
        perimetro = figura2.calcularPerimetro();
        txtRPerimetro.setText(String.valueOf(perimetro));

    }//GEN-LAST:event_btnPerimetroRActionPerformed

    private void btnBorrarRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarRActionPerformed
        // TODO add your handling code here:

        txtRBase.setText("");
        txtRAltura.setText("");
        txtRArea.setText("");
        txtRPerimetro.setText("");
    }//GEN-LAST:event_btnBorrarRActionPerformed

    private void txtRoDiagonal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRoDiagonal1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRoDiagonal1ActionPerformed

    private void txtRoDiagonal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRoDiagonal2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRoDiagonal2ActionPerformed

    private void btnAreaRoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAreaRoActionPerformed
        // TODO add your handling code here:
        double area;
        int diagonal1 = Integer.parseInt(txtRoDiagonal1.getText());
        int diagonal2 = Integer.parseInt(txtRoDiagonal2.getText());
        Rombo figura5 = new Rombo(diagonal1,diagonal2);
        area = figura5.calcularArea();
        txtRoArea.setText(String.valueOf(area));
    }//GEN-LAST:event_btnAreaRoActionPerformed

    private void btnPerimetroRoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerimetroRoActionPerformed
        // TODO add your handling code here:
        double perimetro;
        int diagonal1 = Integer.parseInt(txtRoDiagonal1.getText());
        int diagonal2 = Integer.parseInt(txtRoDiagonal2.getText());
        Rombo figura5 = new Rombo(diagonal1,diagonal2);
        perimetro = figura5.calcularPerimetro();
        txtRoPerimetro.setText(String.valueOf(perimetro));
    }//GEN-LAST:event_btnPerimetroRoActionPerformed

    private void btnBorrarRoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarRoActionPerformed
        // TODO add your handling code here:
        txtRoDiagonal1.setText("");
        txtRoDiagonal2.setText("");
        txtRoArea.setText("");
        txtRoPerimetro.setText("");
    }//GEN-LAST:event_btnBorrarRoActionPerformed

    private void txtTBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTBaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTBaseActionPerformed

    private void txtTAlturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTAlturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTAlturaActionPerformed

    private void btnAreaTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAreaTActionPerformed
        // TODO add your handling code here:

        double area;
        int base = Integer.parseInt(txtTBase.getText());
        int altura = Integer.parseInt(txtTAltura.getText());
        TrianguloRectangulo figura4 = new TrianguloRectangulo(base,altura);
        area = figura4.calcularArea();
        txtTArea.setText(String.valueOf(area));

    }//GEN-LAST:event_btnAreaTActionPerformed

   private void btnPerimetroCActionPerformed() {                                              
        // TODO add your handling code here:
        
        double perimetro;
        int radio = Integer.parseInt(txtCRadio.getText());
        Circulo figura1 = new Circulo(radio);
        perimetro = figura1.calcularPerimetro();
        txtCPerimetro.setText(String.valueOf(perimetro));
    }                                             

    private void txtCAreaActionPerformed() {                                         
        // TODO add your handling code here:
    }                                        

    private void txtCRadioActionPerformed() {                                          
        // TODO add your handling code here:
    }                                         

    private void btnAreaCActionPerformed() {                                         
        // TODO add your handling code here:
        
        double area;
        int radio = Integer.parseInt(txtCRadio.getText());
        Circulo figura1 = new Circulo(radio);
        area = figura1.calcularArea();
        txtCArea.setText(String.valueOf(area));

    }                                        

    private void btnBorrarCActionPerformed() {                                           
        // TODO add your handling code here:
        
        txtCRadio.setText("");
        txtCArea.setText("");
        txtCPerimetro.setText("");
        
    }                                          

    private void txtCuLadoActionPerformed() {                                          
        // TODO add your handling code here:
    }                                         

    private void txtCuAreaActionPerformed() {                                          
        // TODO add your handling code here:
    }                                         

    private void btnAreaCuActionPerformed() {                                          
        // TODO add your handling code here:
        
        double area;
        int lado = Integer.parseInt(txtCuLado.getText());
        Cuadrado figura3 = new Cuadrado(lado);
        area = figura3.calcularArea();
        txtCuArea.setText(String.valueOf(area));

    }                                         

    private void btnPerimetroCuActionPerformed() {                                               
        // TODO add your handling code here:
        double perimetro;
        int lado = Integer.parseInt(txtCuLado.getText());
        Cuadrado figura3 = new Cuadrado(lado);
        perimetro = figura3.calcularPerimetro();
        txtCuPerimetro.setText(String.valueOf(perimetro));
        
    }                                              

    private void btnBorrarCuActionPerformed() {                                            
        // TODO add your handling code here:
        txtCuLado.setText("");
        txtCuArea.setText("");
        txtCuPerimetro.setText("");
    }                                           

    private void txtRBaseActionPerformed() {                                         
        // TODO add your handling code here:
    }                                        

    private void txtRAlturaActionPerformed() {                                           
        // TODO add your handling code here:
    }                                          

    private void btnAreaRActionPerformed() {                                         
        // TODO add your handling code here:
  
        double area;
        int base = Integer.parseInt(txtRBase.getText());
        int altura = Integer.parseInt(txtRAltura.getText());
        Rectangulo figura2 = new Rectangulo(base,altura);
        area = figura2.calcularArea();
        txtRArea.setText(String.valueOf(area));
        
    }                                        

    private void btnPerimetroRActionPerformed() {                                              
        // TODO add your handling code here:
        
        double perimetro;
        int base = Integer.parseInt(txtRBase.getText());
        int altura = Integer.parseInt(txtRAltura.getText());
        Rectangulo figura2 = new Rectangulo(base,altura);
        perimetro = figura2.calcularPerimetro();
        txtRPerimetro.setText(String.valueOf(perimetro));
        
    }                                             

    private void btnBorrarRActionPerformed() {                                           
        // TODO add your handling code here:
        
        txtRBase.setText("");
        txtRAltura.setText("");
        txtRArea.setText("");
        txtRPerimetro.setText("");
    }                                          

    private void txtTBaseActionPerformed() {                                         
        // TODO add your handling code here:
    }                                        

    private void txtTAlturaActionPerformed() {                                           
        // TODO add your handling code here:
    }                                          

    private void btnAreaTActionPerformed() {                                         
        // TODO add your handling code here:
        
        double area;
        int base = Integer.parseInt(txtTBase.getText());
        int altura = Integer.parseInt(txtTAltura.getText());
        TrianguloRectangulo figura4 = new TrianguloRectangulo(base,altura);
        area = figura4.calcularArea();
        txtTArea.setText(String.valueOf(area));
        
    }                                        

    private void btnPerimetroTActionPerformed() {                                              
        // TODO add your handling code here:
        
        double perimetro;
        int base = Integer.parseInt(txtTBase.getText());
        int altura = Integer.parseInt(txtTAltura.getText());
        TrianguloRectangulo figura4 = new TrianguloRectangulo(base,altura);
        perimetro = figura4.calcularPerimetro();
        txtTPerimetro.setText(String.valueOf(perimetro));
        
    }                                             

    private void btnBorrarTActionPerformed() {                                           
        // TODO add your handling code here:
        
        txtTBase.setText("");
        txtTAltura.setText("");
        txtTArea.setText("");
        txtTPerimetro.setText("");
        txtTTipo.setText("");
        
    }                                          

    private void bntTipoTActionPerformed() {                                         
        // TODO add your handling code here:
        
        
        int base = Integer.parseInt(txtTBase.getText());
        int altura = Integer.parseInt(txtTAltura.getText());
        TrianguloRectangulo figura4 = new TrianguloRectangulo(base,altura);
        txtTTipo.setText(figura4.determinarTipoTriangulo());
        
    }                                        

    private void txtTraBase1ActionPerformed() {                                            
        // TODO add your handling code here:
    }                                           

    private void txtTraBase2ActionPerformed() {                                            
        // TODO add your handling code here:
    }                                           

    private void btnAreaTraActionPerformed() {                                           
        // TODO add your handling code here:
        double area;
        int base1 = Integer.parseInt(txtTraBase1.getText());
        int base2 = Integer.parseInt(txtTraBase2.getText());
        int altura = Integer.parseInt(txtTraAltura.getText());
        Trapecio figura6 = new Trapecio(base1,base2,altura);
        area = figura6.calcularArea();
        txtTraArea.setText(String.valueOf(area));
    }                                          

    private void btnPerimetroTraActionPerformed() {                                                
        // TODO add your handling code here:
        double perimetro;
        int base1 = Integer.parseInt(txtTraBase1.getText());
        int base2 = Integer.parseInt(txtTraBase2.getText());
        int altura = Integer.parseInt(txtTraAltura.getText());
        Trapecio figura6 = new Trapecio(base1,base2,altura);
        perimetro = figura6.calcularPerimetro();
        txtTraPerimetro.setText(String.valueOf(perimetro));
    }                                               

    private void btnBorrarTraActionPerformed() {                                             
        // TODO add your handling code here:
        txtTraBase1.setText("");
        txtTraBase2.setText("");
        txtTraAltura.setText("");
        txtTraArea.setText("");
        txtTraPerimetro.setText("");
    }                                            

    private void txtRoDiagonal1ActionPerformed() {                                               
        // TODO add your handling code here:
    }                                              

    private void txtRoDiagonal2ActionPerformed() {                                               
        // TODO add your handling code here:
    }                                              

    private void btnAreaRoActionPerformed() {                                          
        // TODO add your handling code here:
        double area;
        int diagonal1 = Integer.parseInt(txtRoDiagonal1.getText());
        int diagonal2 = Integer.parseInt(txtRoDiagonal2.getText());
        Rombo figura5 = new Rombo(diagonal1,diagonal2);
        area = figura5.calcularArea();
        txtRoArea.setText(String.valueOf(area));
    }                                         

    private void btnPerimetroRoActionPerformed() {                                               
        // TODO add your handling code here:
        double perimetro;
        int diagonal1 = Integer.parseInt(txtRoDiagonal1.getText());
        int diagonal2 = Integer.parseInt(txtRoDiagonal2.getText());
        Rombo figura5 = new Rombo(diagonal1,diagonal2);
        perimetro = figura5.calcularPerimetro();
        txtRoPerimetro.setText(String.valueOf(perimetro));
    }                                              

    private void btnBorrarRoActionPerformed() {                                            
        // TODO add your handling code here:
        txtRoDiagonal1.setText("");
        txtRoDiagonal2.setText("");
        txtRoArea.setText("");       
        txtRoPerimetro.setText("");       
    }                                           
    // Variables declaration - do not modify
                    
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntTipoT;
    private javax.swing.JButton btnAreaC;
    private javax.swing.JButton btnAreaCu;
    private javax.swing.JButton btnAreaR;
    private javax.swing.JButton btnAreaRo;
    private javax.swing.JButton btnAreaT;
    private javax.swing.JButton btnAreaTra;
    private javax.swing.JButton btnBorrarC;
    private javax.swing.JButton btnBorrarCu;
    private javax.swing.JButton btnBorrarR;
    private javax.swing.JButton btnBorrarRo;
    private javax.swing.JButton btnBorrarT;
    private javax.swing.JButton btnBorrarTra;
    private javax.swing.JButton btnPerimetroC;
    private javax.swing.JButton btnPerimetroCu;
    private javax.swing.JButton btnPerimetroR;
    private javax.swing.JButton btnPerimetroRo;
    private javax.swing.JButton btnPerimetroT;
    private javax.swing.JButton btnPerimetroTra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtCArea;
    private javax.swing.JTextField txtCPerimetro;
    private javax.swing.JTextField txtCRadio;
    private javax.swing.JTextField txtCuArea;
    private javax.swing.JTextField txtCuLado;
    private javax.swing.JTextField txtCuPerimetro;
    private javax.swing.JTextField txtRAltura;
    private javax.swing.JTextField txtRArea;
    private javax.swing.JTextField txtRBase;
    private javax.swing.JTextField txtRPerimetro;
    private javax.swing.JTextField txtRoArea;
    private javax.swing.JTextField txtRoDiagonal1;
    private javax.swing.JTextField txtRoDiagonal2;
    private javax.swing.JTextField txtRoPerimetro;
    private javax.swing.JTextField txtTAltura;
    private javax.swing.JTextField txtTArea;
    private javax.swing.JTextField txtTBase;
    private javax.swing.JTextField txtTPerimetro;
    private javax.swing.JTextField txtTTipo;
    private javax.swing.JTextField txtTraAltura;
    private javax.swing.JTextField txtTraArea;
    private javax.swing.JTextField txtTraBase1;
    private javax.swing.JTextField txtTraBase2;
    private javax.swing.JTextField txtTraPerimetro;
    // End of variables declaration//GEN-END:variables
}
